hardocde to known working version without Exception in thread "main" java.lang.NoClassDefFoundError: com/fasterxml/jackson/databind/ObjectMapper 	at org.flywaydb.commandline.Main.main(Main.java:109) Caused by: java.lang.ClassNotFoundException: com.fasterxml.jackson.databind.ObjectMapper 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source) 	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source) 	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)